### ISSUE TITLE
nit : remove 100 max limit

### ISSUE THREAD

**Issue by da-w-xu** [justinabrahms/cribl-interview-python#4]
just a little nit: can we remove the 100 max results config? i'd like to play around with larger numbers

**Comment by justinabrahms** [comment]
@da-w-xu This is undocumented, but you can do that. Set the `MAX_RESULTS` environment variable in the terminal where you start the server to the number you want it to go up to and that'll raise the ceiling.

That said, this isn't really built to scale like mad. :) Have fun.
